version: 2

sources:
  - name: staging
    database: local-scope-455103-k3
    schema: project_dataset

    tables:
      - name: long_data_

models:
  - name: stg_power_consumption
    description: ""
    columns:
      - name: state
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: region
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: latitude
        data_type: int64
        description: ""
      
      - name: longitude
        data_type: int64
        description: ""
      
      - name: date
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: usage
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn
